export class SimulatedProducts {

    /**
     * Produtos simulados
     */

    static products = [
        {id: 0, name: 'Livro - HTML5', price: 48, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/110531/6/110531638GG.jpg', description:'Se você não conhece as novas características disponíveis no HTML5, agora é hora de descobrir. Este livro fornece informações práticas sobre como e porque a última versão dessa linguagem de marcação mudará significativamente a forma como você desenvolve para a Web.'},
        {id: 1, name: 'Livro - Desenvolva Aplicações Web Profissionais com Uso dos Poderosos Recursos de Estilização das CSS3', price: 71, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/110414/4/110414474GG.jpg', description:'CSS3 ultrapassou o status de proposta de uma tecnologia que prometia revolucionar a forma como estilizamos documentos para a web e deve obrigatoriamente fazer parte do dia a dia dos designers e desenvolvedores web.'},
        {id: 2, name: 'Livro - Javascript: O Guia Definitivo', price: 126, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/112167/5/112167569_1GG.jpg', description:'JavaScript é a linguagem de programação da Web. A maioria dos sites modernos usa JavaScript, e todos os navegadores - em computadores de mesa, consoles de jogos, tablets e smartphones - incluem interpretadores JavaScript. Isso a torna uma das linguagens de programação mais importantes atualmente e uma das tecnologias que todo desenvolvedor Web deve conhecer.'},
        {id: 3, name: 'Construindo Apis Rest Com Node.Js', price: 104, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/13465/2/13465237_1GG.jpg', description:'Hoje Em Dia, É Muito Comum Criar Aplicações Client-Side Para Web E Mobile Que Consomem Dados De Uma Api (Application Programming Interface), Que São Sistemas Back-End Focados Apenas No Processamento E Envio De Dados, De Forma Centralizada. Isso Permite Que Sejam Desenvolvidas Múltiplas Aplicações Clientes Com Interfaces Específicas Para Usuários Mobile, Desktop Ou Web. Desde 2010, O Node.Js Provou Ser Uma Excelente Plataforma Escalável Na Solução De Diversos Problemas, Principalmente Para Construção De Apis Restful. Neste Livro, Caio Ribeiro Pereira Mostra Na Prática Os Motivos Por Que Optar Pelo Node.Js, Que É Uma Plataforma Altamente Escalável E De Baixo Nível. Nele, Você Vai Aprender Boas Práticas Sobre Como Construir Uma Api Utilizando Código Ecmascript 2015 (Aka Es6) E Frameworks Populares Como Express, Passport, Apidoc, Mocha E Muito Mais. O Projeto Será Integrado Com Banco De Dados Relacional Através Do Sequelize.Js E, Para Finalizar, Será Construída Uma Aplicação Cliente Web Em Formato Spa (Single Page Application) Utilizando Apenas O Melhor Do Mais Puro Vanilla Javascript.'},
        {id: 4, name: 'Livro - Construindo Aplicações Node Com MongoDB e Backbone', price: 52, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/112678/3/112678369_1GG.jpg', description:'Construa uma aplicação do backend ao navegador com o Node.js e abra as portas para a programação de eventos em tempo real. Com este livro prático, você aprenderá a criar uma aplicação de rede social semelhante ao LinkedIn e ao Facebook, mas com uma pitada de tempo real. E você a construirá com apenas uma linguagem de programação: JavaScript.'},
        {id: 5, name: 'Livro - Construindo Aplicações Com Nodejs', price: 47, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/124507/9/124507962_1GG.jpg', description:'O NodeJS é uma poderosa plataforma para construir de forma rápida e fácil aplicações de rede escaláveis. Utiliza um modelo de single thread, faz I/O não bloqueante e por isso trabalha sempre de forma assíncrona.'},
        {id: 6, name: 'Livro - Use a Cabeça! Python', price: 82, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/112690/7/112690771_1GG.jpg', description:'Sempre quis aprender o Python com um livro? O Use a Cabeça! Python ajuda você a aprender a linguagem, através de um método único que vai além da sintaxe e dos manuais. Você entenderá rapidamente os fundamentos da linguagem Python. Em seguida, passará à persistência, tratamento de exceções, desenvolvimento Web, SQLite, disputas de dados e Google App Engine. Também aprenderá a escrever aplicativos móveis para o Android, tudo graças ao poder que o Python lhe dá.'},
        {id: 7, name: 'Livro - Django Essencial', price: 63, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/123436/9/123436904_1GG.jpg', description:'Como podemos tirar proveito do framework Django para integrar interações complexas do lado cliente e recursos de tempo real em nossas aplicações web? Por meio de uma série de projetos que usam desenvolvimento rápido de aplicações, este livro prático mostra aos desenvolvedores Django experientes de que modo eles podem incluir APIs REST, WebSockets e frameworks MVC do lado cliente, como o Backbone.js, em projetos novos ou existentes.'},
        {id: 8, name: 'Javascript Jquery', price: 141, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/13635/8/13635860_1GG.jpg', description:'Aprenda Javascript e Jquery.'},
        {id: 9, name: 'Livro - Pro Node.Js para Desenvolvedores', price: 86, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/120027/2/120027283_1GG.jpg', description:'Nós apresentamos você ao Node - o que ele é, por que interessa e como configurá-lo - antes de mergulhar fundo nos principais conceitos e APIs que alicerçam sua operação. Partindo da experiência de JavaScript, vamos mostrar como usar o Node.js para construir aplicativos baseados tanto na Web quanto em rede, para tratar com fontes de dados, capturar eventos e lidar com processos filhos para a criação de aplicativos robustos que funcionarão bem numa ampla faixa de situações.'},
        {id: 10, name: 'Smartphone Moto G4 Play DTV Colors Dual Chip Android 6.0 Tela 5 16GB Câmera 8MP - Preto', price: 749, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/128361/2/128361278_1GG.png', description:'O Smartphone Moto G4 Play DTV Colors foi criado para você que quer registrar tudo o que acontece ao seu redor e, ao mesmo tempo, ter uma velocidade super rápida de internet, associada a uma bateria que dura o dia todo.'},
        {id: 11, name: 'Smartphone Meizu M3s 5", Octa Core, Leitor De Biometria, Dual Chip 4g - Cinza', price: 999, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/22093/6/22093608_1GG.jpg', description:'Smartphone Meizu M3s 5", Octa Core, Leitor De Biometria, Dual Chip 4g - Cinza'},
        {id: 12, name: 'iPhone 6S 32GB Dourado Tela 4,7" IOS 4G Câmera 12MP - Apple', price: 2999, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/129252/0/129252073_1GG.jpg', description:'É só começar a usar o iPhone 6S para perceber como ele é diferente de tudo o que você já experimentou. Com o 3D Touch, você faz muito mais em um só toque. Com as Live Photos, suas memórias ganham vida e movimento. E essas são só algumas das novidades. Quando você explora o iPhone 6S a fundo, encontra camadas e camadas de inovação.'},
        {id: 13, name: 'iPhone 7 256GB Preto Brilhante Tela Retina HD 4,7" 3D Touch Câmera 12MP - Apple', price: 3799, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/129610/9/129610918_1GG.jpg', description:'O iPhone 7 melhora consideravelmente as partes mais importantes da sua experência com o iPhone. Ele traz um conjunto de câmeras completamente novo, o melhor desempenho e a maior duração de bateria até hoje, sistema de alto-falantes estéreo e tela com mais brilho e core. Além de ser resistente à água e respingos. É poderoso em cada detalhe. E poderoso como um todo.'},
        {id: 14, name: 'Console PlayStation 4 500GB + Controle Dualshock 4', price: 1221, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/121137/9/121137960_1GG.png', description:'O PlayStation 4 é o melhor lugar para jogar jogos dinâmicos e conectados, com gráfico rico e alta velocidade, personalização inteligente, funcionalidades sociais altamente integradas e recursos de segunda tela inovadores. Combinando conteúdo sem igual, experiências de jogo envolventes, todos os seus aplicativos favoritos de entretenimento digital e as exclusividades do PlayStation, o PS4 é centrado nos jogadores, permitindo-lhes que joguem quando, onde e como quiserem. O PS4 permite que os melhores desenvolvedores de jogos do mundo liberem sua criatividade e estendam os limites do jogo por meio de um sistema que está sintonizado especificamente com suas necessidades.'},
        {id: 15, name: 'Console PS4 Slim 500GB + 2 Jogos + Controle - Sony', price: 1799, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/131722/1/131722134_1GG.jpg', description:'O novo PlayStation 4 Slim abre portas para viagens extraordinárias através de novos mundos de jogos envolventes e uma comunidade de jogadores profundamente conectada. Somente no PlayStation Você veio ao lugar certo. Jogos exclusivos irão te levar a incríveis jornadas, desde indies aclamados pela crítica até premiados sucessos AAA como Uncharted 4: A Thiefs End DUALSHOCK 4. O controle wireless DUALSHOCK 4 apresenta controle familiar incorporando novas formas de interagir com o jogo e outros jogadores. Dois sticks analógicos, barra de luz e botões de disparo oferecem um senso de controle ainda melhor enquanto o touch pad proporciona um potencial infinito de novas possibilidade de jogo.'},
        {id: 16, name: 'Impressora Samsung Multifucional SL-M2070W/XAB Laser Monocromática com Wi-Fi', price: 757, thumb:'https://images-submarino.b2w.io/produtos/01/00/item/120243/5/120243525_1GG.png', description:'Com a Impressora Samsung Laser Monocromática você terá o melhor em qualidade de impressão, rápida e eficaz, a Impressora Samsung Laser é ideal para você que aprecia imagens com nitidez.'}
    ];
}